### ISSUE TITLE
ts声明文件内容错误

### ISSUE THREAD

**Issue by ArvinChen9539** [ryouaki/lsp-uuid#5]
代码上看这个st的参数应该是可以为空的
![image](https://user-images.githubusercontent.com/20532645/203888017-db0bdc16-db7d-4464-8247-0d3f6cdd526e.png)
这个位置应该是 `export function uuid(st?:any):any`

![image](https://user-images.githubusercontent.com/20532645/203888183-c7f64b44-cf12-4567-9cf9-2b53e45d3f98.png)

如果这个声明文件是自动生成的这个位置可以试一下改成下面对不对
`function uuid(st = Date.now()) {}`

现在不传参数编辑器提示有错误
![image](https://user-images.githubusercontent.com/20532645/203888388-61f654aa-8de9-4aa8-bfed-699f6f95166a.png)

**Comment by ryouaki** [comment]
thanks .this issue be fixed.
